FROM node:22-alpine

WORKDIR /app

ARG AUTH_SECRET

ENV AUTH_SECRET=${AUTH_SECRET}
ENV NEXT_TELEMETRY_DISABLED=1

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0"]